### ISSUE TITLE
issue with import

### ISSUE THREAD

**Issue by AIAdventures** [cgnorthcutt/rankpruning#1]
hi really interesting package!

Strange i having some trouble with the import 

andrewcz@andrewcz-PORTEGE-Z30t-B ~ $ python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rankpruning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andrewcz/rankpruning/rankpruning/__init__.py", line 1, in <module>
    from rankpruning import RankPruning
ImportError: cannot import name 'RankPruning'
>>> 

done everything and understand pip and conda package management.
hope you can help.
Many thanks,:)
Andrew

**Comment by AIAdventures** [comment]
![image](https://user-images.githubusercontent.com/26102503/27379070-373599f2-56bd-11e7-9295-66b97d224c05.png)

**Comment by AIAdventures** [comment]
another version of the notebook
Many thanks,
Best,
Andrew

**Comment by philipperemy** [comment]
I have the same error

**Comment by ghost** [comment]
Looks to me like a cyclical import issue; when it says `from rankpruning import ...` in `__init__.py`, it probably attempts a global import first, meaning it re-loads `__init__.py` recursively.

This might be a Python-2 issue; import semantics have improved with time, and in Python 3 you'd do a relative import:

`from .rankpruning import ...`

The leading "." means "load rankpruning.py from the module directory, rather than looking up a module called "rankpruning" and loading that". I'm guessing this was the desired behaviour.

**Comment by zhangpablo** [comment]
I also meet this issue, and I use Python 3.6 and Ubuntu 16.04. I used 'from .rankpruning import ....' instead of 'from rankpruning import' in __int__.py and then fixed it. Thanks.

**Comment by HiJuly** [comment]
good

**Comment by cgnorthcutt** [comment]
Hi folks, Hope you're enjoying this package (rankpruning), which is NOW DEPRECATED. It has been replaced by https://github.com/cgnorthcutt/cleanlab -- which generalizes the package to multi-class learning with noisy labels and supports a wide range of functions for identifying label errors in datasets. You'll want to make the switch as soon as possible. Unlike rankpruning, the cleanlab package supports Python 2 and 3 and has professional support for testing with tox/travisCI/coverage/pytest.
